services:
  - type: web
    name: chatbot-backend
    env: node
    region: oregon
    plan: free
    buildCommand: "cd chatbot-backend && npm install"
    startCommand: "cd chatbot-backend && npm start"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
      - key: JINA_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: QDRANT_COLLECTION_NAME
        value: news_articles
      - key: FRONTEND_URL
        sync: false
